//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp2BytesMusic.ServiceReferenceAlbum {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceAlbum.AlbumSoap")]
    public interface AlbumSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Save", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int Save(WebApp2BytesMusic.ServiceReferenceAlbum.EAlbum album);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Save", ReplyAction="*")]
        System.Threading.Tasks.Task<int> SaveAsync(WebApp2BytesMusic.ServiceReferenceAlbum.EAlbum album);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckExist", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int CheckExist(string albumTitle);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckExist", ReplyAction="*")]
        System.Threading.Tasks.Task<int> CheckExistAsync(string albumTitle);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Read", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Read();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Read", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> ReadAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int Update(WebApp2BytesMusic.ServiceReferenceAlbum.EAlbum album);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update", ReplyAction="*")]
        System.Threading.Tasks.Task<int> UpdateAsync(WebApp2BytesMusic.ServiceReferenceAlbum.EAlbum album);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int Delete(int albumId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        System.Threading.Tasks.Task<int> DeleteAsync(int albumId);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EAlbum : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string titleField;
        
        private string releaseYearField;
        
        private string imagePathField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("Title");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ReleaseYear {
            get {
                return this.releaseYearField;
            }
            set {
                this.releaseYearField = value;
                this.RaisePropertyChanged("ReleaseYear");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ImagePath {
            get {
                return this.imagePathField;
            }
            set {
                this.imagePathField = value;
                this.RaisePropertyChanged("ImagePath");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AlbumSoapChannel : WebApp2BytesMusic.ServiceReferenceAlbum.AlbumSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AlbumSoapClient : System.ServiceModel.ClientBase<WebApp2BytesMusic.ServiceReferenceAlbum.AlbumSoap>, WebApp2BytesMusic.ServiceReferenceAlbum.AlbumSoap {
        
        public AlbumSoapClient() {
        }
        
        public AlbumSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AlbumSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AlbumSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AlbumSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Save(WebApp2BytesMusic.ServiceReferenceAlbum.EAlbum album) {
            return base.Channel.Save(album);
        }
        
        public System.Threading.Tasks.Task<int> SaveAsync(WebApp2BytesMusic.ServiceReferenceAlbum.EAlbum album) {
            return base.Channel.SaveAsync(album);
        }
        
        public int CheckExist(string albumTitle) {
            return base.Channel.CheckExist(albumTitle);
        }
        
        public System.Threading.Tasks.Task<int> CheckExistAsync(string albumTitle) {
            return base.Channel.CheckExistAsync(albumTitle);
        }
        
        public System.Data.DataTable Read() {
            return base.Channel.Read();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ReadAsync() {
            return base.Channel.ReadAsync();
        }
        
        public int Update(WebApp2BytesMusic.ServiceReferenceAlbum.EAlbum album) {
            return base.Channel.Update(album);
        }
        
        public System.Threading.Tasks.Task<int> UpdateAsync(WebApp2BytesMusic.ServiceReferenceAlbum.EAlbum album) {
            return base.Channel.UpdateAsync(album);
        }
        
        public int Delete(int albumId) {
            return base.Channel.Delete(albumId);
        }
        
        public System.Threading.Tasks.Task<int> DeleteAsync(int albumId) {
            return base.Channel.DeleteAsync(albumId);
        }
    }
}
