//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp2BytesMusic.ServiceReferencePlaylistSong {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferencePlaylistSong.PlaylistSongSoap")]
    public interface PlaylistSongSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckExist", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int CheckExist(int playlistId, int songId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckExist", ReplyAction="*")]
        System.Threading.Tasks.Task<int> CheckExistAsync(int playlistId, int songId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Save", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int Save(int playlistId, int songId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Save", ReplyAction="*")]
        System.Threading.Tasks.Task<int> SaveAsync(int playlistId, int songId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Read", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Read(int playlistId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Read", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> ReadAsync(int playlistId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int Delete(int playlistId, int songId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        System.Threading.Tasks.Task<int> DeleteAsync(int playlistId, int songId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteById", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int DeleteById(int playlistId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteById", ReplyAction="*")]
        System.Threading.Tasks.Task<int> DeleteByIdAsync(int playlistId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PlaylistSongSoapChannel : WebApp2BytesMusic.ServiceReferencePlaylistSong.PlaylistSongSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PlaylistSongSoapClient : System.ServiceModel.ClientBase<WebApp2BytesMusic.ServiceReferencePlaylistSong.PlaylistSongSoap>, WebApp2BytesMusic.ServiceReferencePlaylistSong.PlaylistSongSoap {
        
        public PlaylistSongSoapClient() {
        }
        
        public PlaylistSongSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PlaylistSongSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PlaylistSongSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PlaylistSongSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int CheckExist(int playlistId, int songId) {
            return base.Channel.CheckExist(playlistId, songId);
        }
        
        public System.Threading.Tasks.Task<int> CheckExistAsync(int playlistId, int songId) {
            return base.Channel.CheckExistAsync(playlistId, songId);
        }
        
        public int Save(int playlistId, int songId) {
            return base.Channel.Save(playlistId, songId);
        }
        
        public System.Threading.Tasks.Task<int> SaveAsync(int playlistId, int songId) {
            return base.Channel.SaveAsync(playlistId, songId);
        }
        
        public System.Data.DataTable Read(int playlistId) {
            return base.Channel.Read(playlistId);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ReadAsync(int playlistId) {
            return base.Channel.ReadAsync(playlistId);
        }
        
        public int Delete(int playlistId, int songId) {
            return base.Channel.Delete(playlistId, songId);
        }
        
        public System.Threading.Tasks.Task<int> DeleteAsync(int playlistId, int songId) {
            return base.Channel.DeleteAsync(playlistId, songId);
        }
        
        public int DeleteById(int playlistId) {
            return base.Channel.DeleteById(playlistId);
        }
        
        public System.Threading.Tasks.Task<int> DeleteByIdAsync(int playlistId) {
            return base.Channel.DeleteByIdAsync(playlistId);
        }
    }
}
