//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp2BytesMusic.ServiceReferenceArtist {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceArtist.ArtistSoap")]
    public interface ArtistSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveArtist", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int SaveArtist(WebApp2BytesMusic.ServiceReferenceArtist.EArtist artist);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveArtist", ReplyAction="*")]
        System.Threading.Tasks.Task<int> SaveArtistAsync(WebApp2BytesMusic.ServiceReferenceArtist.EArtist artist);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckExistArtist", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int CheckExistArtist(WebApp2BytesMusic.ServiceReferenceArtist.EArtist artist);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckExistArtist", ReplyAction="*")]
        System.Threading.Tasks.Task<int> CheckExistArtistAsync(WebApp2BytesMusic.ServiceReferenceArtist.EArtist artist);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReadArtist", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ReadArtist();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReadArtist", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> ReadArtistAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateArtist", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int UpdateArtist(WebApp2BytesMusic.ServiceReferenceArtist.EArtist artist);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateArtist", ReplyAction="*")]
        System.Threading.Tasks.Task<int> UpdateArtistAsync(WebApp2BytesMusic.ServiceReferenceArtist.EArtist artist);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteArtist", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int DeleteArtist(int artistId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteArtist", ReplyAction="*")]
        System.Threading.Tasks.Task<int> DeleteArtistAsync(int artistId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ArtistValidations", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ArtistValidations(WebApp2BytesMusic.ServiceReferenceArtist.EArtist artist);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ArtistValidations", ReplyAction="*")]
        System.Threading.Tasks.Task<string> ArtistValidationsAsync(WebApp2BytesMusic.ServiceReferenceArtist.EArtist artist);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EArtist : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string firstNameField;
        
        private string lastNameField;
        
        private string imagePathField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
                this.RaisePropertyChanged("FirstName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
                this.RaisePropertyChanged("LastName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ImagePath {
            get {
                return this.imagePathField;
            }
            set {
                this.imagePathField = value;
                this.RaisePropertyChanged("ImagePath");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ArtistSoapChannel : WebApp2BytesMusic.ServiceReferenceArtist.ArtistSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ArtistSoapClient : System.ServiceModel.ClientBase<WebApp2BytesMusic.ServiceReferenceArtist.ArtistSoap>, WebApp2BytesMusic.ServiceReferenceArtist.ArtistSoap {
        
        public ArtistSoapClient() {
        }
        
        public ArtistSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ArtistSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ArtistSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ArtistSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int SaveArtist(WebApp2BytesMusic.ServiceReferenceArtist.EArtist artist) {
            return base.Channel.SaveArtist(artist);
        }
        
        public System.Threading.Tasks.Task<int> SaveArtistAsync(WebApp2BytesMusic.ServiceReferenceArtist.EArtist artist) {
            return base.Channel.SaveArtistAsync(artist);
        }
        
        public int CheckExistArtist(WebApp2BytesMusic.ServiceReferenceArtist.EArtist artist) {
            return base.Channel.CheckExistArtist(artist);
        }
        
        public System.Threading.Tasks.Task<int> CheckExistArtistAsync(WebApp2BytesMusic.ServiceReferenceArtist.EArtist artist) {
            return base.Channel.CheckExistArtistAsync(artist);
        }
        
        public System.Data.DataTable ReadArtist() {
            return base.Channel.ReadArtist();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ReadArtistAsync() {
            return base.Channel.ReadArtistAsync();
        }
        
        public int UpdateArtist(WebApp2BytesMusic.ServiceReferenceArtist.EArtist artist) {
            return base.Channel.UpdateArtist(artist);
        }
        
        public System.Threading.Tasks.Task<int> UpdateArtistAsync(WebApp2BytesMusic.ServiceReferenceArtist.EArtist artist) {
            return base.Channel.UpdateArtistAsync(artist);
        }
        
        public int DeleteArtist(int artistId) {
            return base.Channel.DeleteArtist(artistId);
        }
        
        public System.Threading.Tasks.Task<int> DeleteArtistAsync(int artistId) {
            return base.Channel.DeleteArtistAsync(artistId);
        }
        
        public string ArtistValidations(WebApp2BytesMusic.ServiceReferenceArtist.EArtist artist) {
            return base.Channel.ArtistValidations(artist);
        }
        
        public System.Threading.Tasks.Task<string> ArtistValidationsAsync(WebApp2BytesMusic.ServiceReferenceArtist.EArtist artist) {
            return base.Channel.ArtistValidationsAsync(artist);
        }
    }
}
